-- =============================================================================
-- Blog migration for production (schema + data + production image URLs)
-- Generated: 2026-05-28T21:24:20.735Z
-- Posts: 5  |  Blocks: 34  |  Images: 6
-- Safe to run multiple times (fully idempotent).
-- Does NOT touch: products, user_profiles, customer_orders or any other table.
-- =============================================================================

-- ---------------------------------------------------------------------------
-- 1. blog_posts table
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS blog_posts (
  id            uuid        PRIMARY KEY DEFAULT gen_random_uuid(),
  title         text        NOT NULL,
  slug          text        NOT NULL UNIQUE,
  eyebrow       text,
  excerpt       text,
  cover_image   text,
  read_time     text,
  published_at  date,
  is_featured   boolean     NOT NULL DEFAULT false,
  published     boolean     NOT NULL DEFAULT false,
  show_in_list  boolean     NOT NULL DEFAULT true,
  created_at    timestamptz NOT NULL DEFAULT now()
);
ALTER TABLE blog_posts ADD COLUMN IF NOT EXISTS show_in_list boolean NOT NULL DEFAULT true;

-- ---------------------------------------------------------------------------
-- 2. blog_blocks table
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS blog_blocks (
  id        uuid    PRIMARY KEY DEFAULT gen_random_uuid(),
  post_id   uuid    NOT NULL REFERENCES blog_posts(id) ON DELETE CASCADE,
  type      text    NOT NULL DEFAULT 'text',
  content   text,
  position  integer NOT NULL DEFAULT 1
);
CREATE INDEX IF NOT EXISTS blog_blocks_post_id_idx ON blog_blocks(post_id);
DO $$ DECLARE r RECORD; BEGIN FOR r IN (
  SELECT conname FROM pg_constraint c JOIN pg_class t ON c.conrelid = t.oid
  WHERE t.relname = 'blog_blocks' AND c.contype = 'c' AND pg_get_constraintdef(c.oid) ILIKE '%type%'
) LOOP EXECUTE format('ALTER TABLE blog_blocks DROP CONSTRAINT %I', r.conname); END LOOP; END; $$;
ALTER TABLE blog_blocks ADD CONSTRAINT blog_blocks_type_check CHECK (type IN ('text', 'image'));

-- ---------------------------------------------------------------------------
-- 3. Row-level security
-- ---------------------------------------------------------------------------
ALTER TABLE blog_posts  ENABLE ROW LEVEL SECURITY;
ALTER TABLE blog_blocks ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN CREATE POLICY "public read published posts" ON blog_posts FOR SELECT USING (published = true); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN CREATE POLICY "public read blocks of published posts" ON blog_blocks FOR SELECT USING (EXISTS (SELECT 1 FROM blog_posts p WHERE p.id = blog_blocks.post_id AND p.published = true)); EXCEPTION WHEN duplicate_object THEN NULL; END $$;

-- ---------------------------------------------------------------------------
-- 4. blog-images storage bucket
-- ---------------------------------------------------------------------------
INSERT INTO storage.buckets (id, name, public, file_size_limit, allowed_mime_types) VALUES ('blog-images', 'blog-images', true, 5242880, ARRAY['image/jpeg','image/png','image/webp','image/gif','image/avif']) ON CONFLICT (id) DO NOTHING;
DO $$ BEGIN CREATE POLICY "blog-images public read" ON storage.objects FOR SELECT USING (bucket_id = 'blog-images'); EXCEPTION WHEN duplicate_object THEN NULL; END $$;

-- ---------------------------------------------------------------------------
-- 5. Data — blog_posts (5 rows, production URLs)
-- ---------------------------------------------------------------------------
INSERT INTO blog_posts (id, title, slug, eyebrow, excerpt, cover_image, read_time, published_at, is_featured, published, show_in_list, created_at) VALUES ('554e860c-f5be-464f-aca8-480a32431615', 'Шафранът: деликатна сила', 'shafranat-sila-ot-prirodata', 'Натурални съставки', 'Зад фините нишки на шафрана стои съставка с характер, история и място в модерната ботанична козметика.', 'https://dzvzfblmyixazofhrxrt.supabase.co/storage/v1/object/public/blog-images/cover-shafranat-sila-ot-prirodata.jpg', '3 мин', '2026-05-03', FALSE, TRUE, TRUE, '2026-05-10T06:48:20.801032') ON CONFLICT (id) DO UPDATE SET title='Шафранът: деликатна сила', slug='shafranat-sila-ot-prirodata', eyebrow='Натурални съставки', excerpt='Зад фините нишки на шафрана стои съставка с характер, история и място в модерната ботанична козметика.', cover_image='https://dzvzfblmyixazofhrxrt.supabase.co/storage/v1/object/public/blog-images/cover-shafranat-sila-ot-prirodata.jpg', read_time='3 мин', published_at='2026-05-03', is_featured=FALSE, published=TRUE, show_in_list=TRUE;
INSERT INTO blog_posts (id, title, slug, eyebrow, excerpt, cover_image, read_time, published_at, is_featured, published, show_in_list, created_at) VALUES ('a8545fe0-ebd5-4257-9782-606b7caf657a', 'Красота и баланс', 'krasota-i-balans-sas-shafran', 'Ритуали за лице', 'Когато една съставка носи и настроение, и грижа, тя лесно намира място в рутината. Шафранът е точно такъв пример.', 'https://dzvzfblmyixazofhrxrt.supabase.co/storage/v1/object/public/blog-images/cover-krasota-i-balans-sas-shafran.jpg', '5 мин', '2026-05-02', FALSE, TRUE, TRUE, '2026-05-10T06:48:20.801032') ON CONFLICT (id) DO UPDATE SET title='Красота и баланс', slug='krasota-i-balans-sas-shafran', eyebrow='Ритуали за лице', excerpt='Когато една съставка носи и настроение, и грижа, тя лесно намира място в рутината. Шафранът е точно такъв пример.', cover_image='https://dzvzfblmyixazofhrxrt.supabase.co/storage/v1/object/public/blog-images/cover-krasota-i-balans-sas-shafran.jpg', read_time='5 мин', published_at='2026-05-02', is_featured=FALSE, published=TRUE, show_in_list=TRUE;
INSERT INTO blog_posts (id, title, slug, eyebrow, excerpt, cover_image, read_time, published_at, is_featured, published, show_in_list, created_at) VALUES ('6ce7eb55-752a-4e4d-b63b-015fe8840016', 'Шафранът в козметиката', 'shafranat-v-kozmetikata', 'Активна грижа', 'Шафранът е сред най-ценните растителни съставки в козметиката. Той носи усещане за комфорт, подкрепя сияйния вид на кожата и прави рутината по-специална.', 'https://dzvzfblmyixazofhrxrt.supabase.co/storage/v1/object/public/blog-images/cover-shafranat-v-kozmetikata.jpg', '4 мин', '2026-05-04', TRUE, TRUE, TRUE, '2026-05-10T06:48:20.801032') ON CONFLICT (id) DO UPDATE SET title='Шафранът в козметиката', slug='shafranat-v-kozmetikata', eyebrow='Активна грижа', excerpt='Шафранът е сред най-ценните растителни съставки в козметиката. Той носи усещане за комфорт, подкрепя сияйния вид на кожата и прави рутината по-специална.', cover_image='https://dzvzfblmyixazofhrxrt.supabase.co/storage/v1/object/public/blog-images/cover-shafranat-v-kozmetikata.jpg', read_time='4 мин', published_at='2026-05-04', is_featured=TRUE, published=TRUE, show_in_list=TRUE;
INSERT INTO blog_posts (id, title, slug, eyebrow, excerpt, cover_image, read_time, published_at, is_featured, published, show_in_list, created_at) VALUES ('386bc6b1-b1e6-4c83-975a-8d7fa8db440a', 'Тест Статия', 'test-statiya', 'Грижа за косата', 'Това е тестови текст т', 'https://dzvzfblmyixazofhrxrt.supabase.co/storage/v1/object/public/blog-images/1778441744713-gm76k813a4.jpg', NULL, '2026-05-10', FALSE, FALSE, TRUE, '2026-05-10T08:08:54.098418') ON CONFLICT (id) DO UPDATE SET title='Тест Статия', slug='test-statiya', eyebrow='Грижа за косата', excerpt='Това е тестови текст т', cover_image='https://dzvzfblmyixazofhrxrt.supabase.co/storage/v1/object/public/blog-images/1778441744713-gm76k813a4.jpg', read_time=NULL, published_at='2026-05-10', is_featured=FALSE, published=FALSE, show_in_list=TRUE;
INSERT INTO blog_posts (id, title, slug, eyebrow, excerpt, cover_image, read_time, published_at, is_featured, published, show_in_list, created_at) VALUES ('3b29994e-f054-4ba9-b741-2af21df01bc7', 'Тест2', 'test2', 'асдфг', 'асд асд с сд', 'https://dzvzfblmyixazofhrxrt.supabase.co/storage/v1/object/public/blog-images/1779992501026-myfv5sndl3e.png', NULL, '2026-05-11', FALSE, FALSE, TRUE, '2026-05-28T18:21:53.216765') ON CONFLICT (id) DO UPDATE SET title='Тест2', slug='test2', eyebrow='асдфг', excerpt='асд асд с сд', cover_image='https://dzvzfblmyixazofhrxrt.supabase.co/storage/v1/object/public/blog-images/1779992501026-myfv5sndl3e.png', read_time=NULL, published_at='2026-05-11', is_featured=FALSE, published=FALSE, show_in_list=TRUE;

-- ---------------------------------------------------------------------------
-- 6. Data — blog_blocks (34 rows, production URLs)
-- ---------------------------------------------------------------------------
INSERT INTO blog_blocks (id, post_id, type, content, position) VALUES ('87189de4-98a0-4dc6-838f-2580f648c7ab', '386bc6b1-b1e6-4c83-975a-8d7fa8db440a', 'text', '<h2>фгхфгх фгхф фг гфгф</h2>', 1) ON CONFLICT (id) DO UPDATE SET type='text', content='<h2>фгхфгх фгхф фг гфгф</h2>', position=1;
INSERT INTO blog_blocks (id, post_id, type, content, position) VALUES ('c050a461-3fa3-4331-a637-80cea9c64346', '386bc6b1-b1e6-4c83-975a-8d7fa8db440a', 'text', '<ul><li><p>фгхфгх</p></li></ul><p></p>', 2) ON CONFLICT (id) DO UPDATE SET type='text', content='<ul><li><p>фгхфгх</p></li></ul><p></p>', position=2;
INSERT INTO blog_blocks (id, post_id, type, content, position) VALUES ('69b13dbc-500f-4c09-954c-3f2e28723d17', '3b29994e-f054-4ba9-b741-2af21df01bc7', 'text', '<h2>ьфцгдф</h2>', 1) ON CONFLICT (id) DO UPDATE SET type='text', content='<h2>ьфцгдф</h2>', position=1;
INSERT INTO blog_blocks (id, post_id, type, content, position) VALUES ('524a3369-16b0-463b-b580-1dcf377c3c65', '3b29994e-f054-4ba9-b741-2af21df01bc7', 'image', '{"url":"https://dzvzfblmyixazofhrxrt.supabase.co/storage/v1/object/public/blog-images/1779994900121-pcey4t9j7eo.png","alt":"гхй йхг хйг хй","caption":""}', 2) ON CONFLICT (id) DO UPDATE SET type='image', content='{"url":"https://dzvzfblmyixazofhrxrt.supabase.co/storage/v1/object/public/blog-images/1779994900121-pcey4t9j7eo.png","alt":"гхй йхг хйг хй","caption":""}', position=2;
INSERT INTO blog_blocks (id, post_id, type, content, position) VALUES ('efe69ee2-be7e-4bc8-97d5-ca977e1967be', '3b29994e-f054-4ba9-b741-2af21df01bc7', 'text', '<p>хъуи  йхг ъ уи уъг хйг хй</p>', 3) ON CONFLICT (id) DO UPDATE SET type='text', content='<p>хъуи  йхг ъ уи уъг хйг хй</p>', position=3;
INSERT INTO blog_blocks (id, post_id, type, content, position) VALUES ('a7fe681d-8c4f-44f1-9e3c-5e71a74b78a6', '3b29994e-f054-4ba9-b741-2af21df01bc7', 'text', '<h2>г йхг</h2>', 4) ON CONFLICT (id) DO UPDATE SET type='text', content='<h2>г йхг</h2>', position=4;
INSERT INTO blog_blocks (id, post_id, type, content, position) VALUES ('c29c42ba-20d6-4f1b-95d7-6a5aa1fc98ff', '3b29994e-f054-4ba9-b741-2af21df01bc7', 'text', '<p>йкъу<strong><em> хйг  гхг хг </em></strong> гйх г</p>', 5) ON CONFLICT (id) DO UPDATE SET type='text', content='<p>йкъу<strong><em> хйг  гхг хг </em></strong> гйх г</p>', position=5;
INSERT INTO blog_blocks (id, post_id, type, content, position) VALUES ('f7b59029-d87b-41b5-b56d-727a78b1c2f4', '554e860c-f5be-464f-aca8-480a32431615', 'text', '<p>Когато говорим за ботанична козметика с ясно присъствие, шафранът винаги изпъква. Той не е просто екзотичен акцент, а съставка, която носи стойност и характер в една формула.</p>', 1) ON CONFLICT (id) DO UPDATE SET type='text', content='<p>Когато говорим за ботанична козметика с ясно присъствие, шафранът винаги изпъква. Той не е просто екзотичен акцент, а съставка, която носи стойност и характер в една формула.</p>', position=1;
INSERT INTO blog_blocks (id, post_id, type, content, position) VALUES ('4fe2552a-5bd8-4407-b91b-e790909d64b9', '554e860c-f5be-464f-aca8-480a32431615', 'text', '<h2>От растение към ритуал</h2>', 2) ON CONFLICT (id) DO UPDATE SET type='text', content='<h2>От растение към ритуал</h2>', position=2;
INSERT INTO blog_blocks (id, post_id, type, content, position) VALUES ('207f0604-bc60-4de6-952e-fab15fe22f84', '554e860c-f5be-464f-aca8-480a32431615', 'text', '<p>Силата на шафрана не е в агресивното действие, а в неговата фина роля. Той работи най-добре в продукти, които са създадени да подкрепят кожата с внимание и постоянство.</p>', 3) ON CONFLICT (id) DO UPDATE SET type='text', content='<p>Силата на шафрана не е в агресивното действие, а в неговата фина роля. Той работи най-добре в продукти, които са създадени да подкрепят кожата с внимание и постоянство.</p>', position=3;
INSERT INTO blog_blocks (id, post_id, type, content, position) VALUES ('76a59fae-b629-4e16-bf5a-c5bb6e23b015', '554e860c-f5be-464f-aca8-480a32431615', 'text', '<p>Именно затова често се среща в рутини, които поставят на първо място комфорта, меката текстура и усещането за добре поддържана кожа.</p>', 4) ON CONFLICT (id) DO UPDATE SET type='text', content='<p>Именно затова често се среща в рутини, които поставят на първо място комфорта, меката текстура и усещането за добре поддържана кожа.</p>', position=4;
INSERT INTO blog_blocks (id, post_id, type, content, position) VALUES ('547e9e46-c157-4911-8f47-16ad12ffae9a', '554e860c-f5be-464f-aca8-480a32431615', 'text', '<h2>Лукс без излишна тежест</h2>', 5) ON CONFLICT (id) DO UPDATE SET type='text', content='<h2>Лукс без излишна тежест</h2>', position=5;
INSERT INTO blog_blocks (id, post_id, type, content, position) VALUES ('f64b5645-228d-4e81-b163-29cae95a6f6d', '554e860c-f5be-464f-aca8-480a32431615', 'text', '<p>Добре формулираната грижа с шафран не стои тежко върху кожата. Тя съчетава усещане за лукс с лекота, което е особено важно за ежедневни продукти.</p>', 6) ON CONFLICT (id) DO UPDATE SET type='text', content='<p>Добре формулираната грижа с шафран не стои тежко върху кожата. Тя съчетава усещане за лукс с лекота, което е особено важно за ежедневни продукти.</p>', position=6;
INSERT INTO blog_blocks (id, post_id, type, content, position) VALUES ('1bb81c7b-5a11-470f-b9a8-8ff5edfa9f1d', '554e860c-f5be-464f-aca8-480a32431615', 'text', '<p>Това е една от причините шафранът да се цени в модерната козметика: придава идентичност, без да прави рутината сложна.</p>', 7) ON CONFLICT (id) DO UPDATE SET type='text', content='<p>Това е една от причините шафранът да се цени в модерната козметика: придава идентичност, без да прави рутината сложна.</p>', position=7;
INSERT INTO blog_blocks (id, post_id, type, content, position) VALUES ('36473f57-bce0-478c-94e2-2abbb331c0d6', '6ce7eb55-752a-4e4d-b63b-015fe8840016', 'text', '<p>Шафранът е познат от векове като ценна природна суровина. В съвременната козметика той се използва не само заради луксозния си образ, а и заради способността си да прави формулите по-деликатни, по-приятни и по-вдъхновяващи за ежедневна употреба.</p>', 1) ON CONFLICT (id) DO UPDATE SET type='text', content='<p>Шафранът е познат от векове като ценна природна суровина. В съвременната козметика той се използва не само заради луксозния си образ, а и заради способността си да прави формулите по-деликатни, по-приятни и по-вдъхновяващи за ежедневна употреба.</p>', position=1;
INSERT INTO blog_blocks (id, post_id, type, content, position) VALUES ('3f433799-f2a3-4c7b-ace8-bf31c9f90f98', '6ce7eb55-752a-4e4d-b63b-015fe8840016', 'text', '<h2>Защо шафранът е толкова ценен</h2>', 2) ON CONFLICT (id) DO UPDATE SET type='text', content='<h2>Защо шафранът е толкова ценен</h2>', position=2;
INSERT INTO blog_blocks (id, post_id, type, content, position) VALUES ('4cdaad6f-08a9-4ab0-8088-5551d2810971', '6ce7eb55-752a-4e4d-b63b-015fe8840016', 'text', '<p>Шафранът се добива трудно и внимателно, което го превръща в една от най-специалните съставки в света на красотата. Малкото количество, което е нужно за една формула, често е достатъчно, за да внесе усещане за премиум грижа.</p>', 3) ON CONFLICT (id) DO UPDATE SET type='text', content='<p>Шафранът се добива трудно и внимателно, което го превръща в една от най-специалните съставки в света на красотата. Малкото количество, което е нужно за една формула, често е достатъчно, за да внесе усещане за премиум грижа.</p>', position=3;
INSERT INTO blog_blocks (id, post_id, type, content, position) VALUES ('e1408e24-951d-4b9e-af9d-a8aeba951090', '6ce7eb55-752a-4e4d-b63b-015fe8840016', 'text', '<p>Той се асоциира с богато съдържание на растителни съединения и се включва във формули, насочени към по-свеж, озарен и равномерен вид на кожата.</p>', 4) ON CONFLICT (id) DO UPDATE SET type='text', content='<p>Той се асоциира с богато съдържание на растителни съединения и се включва във формули, насочени към по-свеж, озарен и равномерен вид на кожата.</p>', position=4;
INSERT INTO blog_blocks (id, post_id, type, content, position) VALUES ('bb299484-d4b2-407d-a9af-4f93c27cd2fb', '6ce7eb55-752a-4e4d-b63b-015fe8840016', 'text', '<h2>Какво носи на кожата</h2>', 5) ON CONFLICT (id) DO UPDATE SET type='text', content='<h2>Какво носи на кожата</h2>', position=5;
INSERT INTO blog_blocks (id, post_id, type, content, position) VALUES ('acab3f0b-b20c-4c4f-bb0c-764ac49f8829', '6ce7eb55-752a-4e4d-b63b-015fe8840016', 'text', '<p>Козметиката с шафран обикновено е насочена към комфорт, мекота и видимо по-жизнен тен. Когато е комбиниран с подхранващи масла и успокояващи растителни екстракти, шафранът допринася за по-завършено усещане след нанасяне.</p>', 6) ON CONFLICT (id) DO UPDATE SET type='text', content='<p>Козметиката с шафран обикновено е насочена към комфорт, мекота и видимо по-жизнен тен. Когато е комбиниран с подхранващи масла и успокояващи растителни екстракти, шафранът допринася за по-завършено усещане след нанасяне.</p>', position=6;
INSERT INTO blog_blocks (id, post_id, type, content, position) VALUES ('0cb2e20a-441b-4c60-8fd4-8f8eb5d0636d', '6ce7eb55-752a-4e4d-b63b-015fe8840016', 'text', '<p>Това го прави подходящ избор за рутини, в които се търси нежен блясък и грижа, която да не натоварва кожата.</p>', 7) ON CONFLICT (id) DO UPDATE SET type='text', content='<p>Това го прави подходящ избор за рутини, в които се търси нежен блясък и грижа, която да не натоварва кожата.</p>', position=7;
INSERT INTO blog_blocks (id, post_id, type, content, position) VALUES ('338b2294-b581-462e-b073-86d2fd537e96', '6ce7eb55-752a-4e4d-b63b-015fe8840016', 'text', '<h2>Къде се вписва най-добре</h2>', 8) ON CONFLICT (id) DO UPDATE SET type='text', content='<h2>Къде се вписва най-добре</h2>', position=8;
INSERT INTO blog_blocks (id, post_id, type, content, position) VALUES ('5d7e06df-c6c4-406c-bff7-5441772aad0a', '6ce7eb55-752a-4e4d-b63b-015fe8840016', 'text', '<p>Шафранът може да присъства в серуми, кремове, маски и масла за лице. Най-често се избира във вечерни ритуали или в продукти, с които искаме да превърнем ежедневната грижа в малък момент на внимание към себе си.</p>', 9) ON CONFLICT (id) DO UPDATE SET type='text', content='<p>Шафранът може да присъства в серуми, кремове, маски и масла за лице. Най-често се избира във вечерни ритуали или в продукти, с които искаме да превърнем ежедневната грижа в малък момент на внимание към себе си.</p>', position=9;
INSERT INTO blog_blocks (id, post_id, type, content, position) VALUES ('0f7f344a-0fac-4394-869d-1696c6ff06ee', '6ce7eb55-752a-4e4d-b63b-015fe8840016', 'text', '<p>Когато формулата е балансирана, той се комбинира отлично с флорални води, леки растителни масла и съставки, които поддържат кожната бариера.</p>', 10) ON CONFLICT (id) DO UPDATE SET type='text', content='<p>Когато формулата е балансирана, той се комбинира отлично с флорални води, леки растителни масла и съставки, които поддържат кожната бариера.</p>', position=10;
INSERT INTO blog_blocks (id, post_id, type, content, position) VALUES ('4d8b7976-2cc5-40ec-b808-b7c8aff28290', 'a8545fe0-ebd5-4257-9782-606b7caf657a', 'text', '<p>Красотата и доброто усещане често започват от малките навици. Продуктите с шафран добавят към тях чувство за мекота, фина грижа и по-изискано преживяване пред огледалото.</p>', 1) ON CONFLICT (id) DO UPDATE SET type='text', content='<p>Красотата и доброто усещане често започват от малките навици. Продуктите с шафран добавят към тях чувство за мекота, фина грижа и по-изискано преживяване пред огледалото.</p>', position=1;
INSERT INTO blog_blocks (id, post_id, type, content, position) VALUES ('c552e86c-69cb-4d46-a7a3-f115857da06b', 'a8545fe0-ebd5-4257-9782-606b7caf657a', 'text', '<h2>Грижата започва с последователност</h2>', 2) ON CONFLICT (id) DO UPDATE SET type='text', content='<h2>Грижата започва с последователност</h2>', position=2;
INSERT INTO blog_blocks (id, post_id, type, content, position) VALUES ('d6bc8b5b-8d68-43fd-9769-2c9eead3e1ae', 'a8545fe0-ebd5-4257-9782-606b7caf657a', 'text', '<p>Не е нужно една рутина да бъде дълга, за да бъде ефективна. По-важно е продуктите в нея да работят в синхрон и да подкрепят кожата ден след ден.</p>', 3) ON CONFLICT (id) DO UPDATE SET type='text', content='<p>Не е нужно една рутина да бъде дълга, за да бъде ефективна. По-важно е продуктите в нея да работят в синхрон и да подкрепят кожата ден след ден.</p>', position=3;
INSERT INTO blog_blocks (id, post_id, type, content, position) VALUES ('539b7c58-1e15-489c-96b1-643f1fe370ca', 'a8545fe0-ebd5-4257-9782-606b7caf657a', 'text', '<p>Шафранът се вписва добре именно в такива режими: внимателни, балансирани и насочени към здрав вид, а не към бързи крайности.</p>', 4) ON CONFLICT (id) DO UPDATE SET type='text', content='<p>Шафранът се вписва добре именно в такива режими: внимателни, балансирани и насочени към здрав вид, а не към бързи крайности.</p>', position=4;
INSERT INTO blog_blocks (id, post_id, type, content, position) VALUES ('d58a3afa-b583-4554-8458-5ebcc17b797c', 'a8545fe0-ebd5-4257-9782-606b7caf657a', 'text', '<h2>Как да го комбинираме</h2>', 5) ON CONFLICT (id) DO UPDATE SET type='text', content='<h2>Как да го комбинираме</h2>', position=5;
INSERT INTO blog_blocks (id, post_id, type, content, position) VALUES ('96d2a530-701a-42fd-a274-efa262270881', 'a8545fe0-ebd5-4257-9782-606b7caf657a', 'text', '<p>Комбинацията с нежно измиване, хидратиращ серум и крем с растителни масла е добра база за рутина със шафран. Така съставката има пространство да разгърне мекото си присъствие.</p>', 6) ON CONFLICT (id) DO UPDATE SET type='text', content='<p>Комбинацията с нежно измиване, хидратиращ серум и крем с растителни масла е добра база за рутина със шафран. Така съставката има пространство да разгърне мекото си присъствие.</p>', position=6;
INSERT INTO blog_blocks (id, post_id, type, content, position) VALUES ('3f203e75-6f8a-41ac-bef3-9d9fe804fd5d', 'a8545fe0-ebd5-4257-9782-606b7caf657a', 'text', '<p>При вечерна грижа може да се добави и маска или по-плътен крем, за да се подсили усещането за подхранване и комфорт.</p>', 7) ON CONFLICT (id) DO UPDATE SET type='text', content='<p>При вечерна грижа може да се добави и маска или по-плътен крем, за да се подсили усещането за подхранване и комфорт.</p>', position=7;
INSERT INTO blog_blocks (id, post_id, type, content, position) VALUES ('98d4f2ac-e4e2-4393-bf2a-21148653fbbe', 'a8545fe0-ebd5-4257-9782-606b7caf657a', 'text', '<h2>Повече от красива съставка</h2>', 8) ON CONFLICT (id) DO UPDATE SET type='text', content='<h2>Повече от красива съставка</h2>', position=8;
INSERT INTO blog_blocks (id, post_id, type, content, position) VALUES ('01d0d33a-64d3-4b7c-9706-be5913bf95f5', 'a8545fe0-ebd5-4257-9782-606b7caf657a', 'text', '<p>Шафранът присъства в козметиката и като символ на отношение към детайла. Той подсказва, че формулата е мислена не само като функция, а и като преживяване.</p>', 9) ON CONFLICT (id) DO UPDATE SET type='text', content='<p>Шафранът присъства в козметиката и като символ на отношение към детайла. Той подсказва, че формулата е мислена не само като функция, а и като преживяване.</p>', position=9;
INSERT INTO blog_blocks (id, post_id, type, content, position) VALUES ('c7f65658-f47b-43c1-b87d-a9de77832def', 'a8545fe0-ebd5-4257-9782-606b7caf657a', 'text', '<p>Точно затова той остава актуален избор за хора, които търсят естествена грижа с ясно изразен характер.</p>', 10) ON CONFLICT (id) DO UPDATE SET type='text', content='<p>Точно затова той остава актуален избор за хора, които търсят естествена грижа с ясно изразен характер.</p>', position=10;

-- Done.